#! /bin/bash
#

/Users/lisa/Dev/visual-trace-app/webtreath-darwin-x64/webtreath.app/Contents/MacOS/webtreath
#/Users/lisa/Dev/visual-trace-app/webthreat-darwin-x64/webthreat.app/Contents/MacOS/webthreat
